version: '3'
services:
  db:
    image: postgres
    ports:
      - '5433:5433'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: booksdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
